---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-objects
spec:
  hard:
    pods: "15"
    services: "10"
    secrets: "10"
    configmaps: "10"
    replicationcontrollers: "1"
    persistentvolumeclaims: "15"
    requests.storage: "15Gi"
    services.loadbalancers: "2"
    services.nodeports: "0"
