---
- hosts: nodes
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
 #   - name: Garantindo /etc/hosts
 #     lineinfile:
 #       path: /etc/hosts
 #       line: "{{ item }}"
 #     with_items:
 #       - 35.226.184.47 master-aluno-21
 #       - 34.135.226.20 node1-aluno-21
 #       - 35.192.168.27 node2-aluno-21
 #       - 104.154.141.115 extras-aluno-21
        
    - name: Instalando dependecias
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - curl 
        - vim 
        - device-mapper-persistent-data 
        - lvm2 
        - epel-release 
        - wget 
        - git 
        - net-tools 
        - bind-utils 
        - yum-utils 
        - iptables-services 
        - bridge-utils 
        - bash-completion 
        - kexec-tools 
        - sos 
        - psacct 
        - docker 
        - python-ipaddress 
        - PyYAML 

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
   
    - name: Docker pull origin-node:v3.11
      shell: docker pull quay.io/openshift/origin-node:v3.11

    - name: Docker pull origin-pod:v3.11
      shell: docker pull quay.io/openshift/origin-pod:v3.11